version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    command: npm start

volumes:
  uploads:
  results:

